server:
  port: 9004

spring:
  application:
    name: wms-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8849
        # 指定集群名称
        cluster-name: BJ
        metadata:
          version: v1